# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          'The Jekyll Butler'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
