# Dependencies
markdown:         kramdown
highlighter:      pygments
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'React Hot Loader'
tagline:          'Tweak React components in real time.'
description:      'Tweak React components in real time.'
url:              http://localhost:4000
paginate:         1
baseurl:          /react-hot-loader
author:
  name:           Dan Abramov
  url:            https://twitter.com/dan_abramov
  email:          dan.abramov@me.com

# Custom vars
version:          0.2.0
github:
  repo:           http://github.com/gaearon/react-hot-loader
