# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            react-hot-loader
url:              //gaearon.github.io
paginate:         1
baseurl:          /react-hot-loader
author:
  name:           Dan Abramov
  url:            https://twitter.com/dan_abramov
  email:          dan.abramov@me.com

# Custom vars
version:          0.2.0
github:
  repo:           http://github.com/gaearon/react-hot-loader
